// import "../../../public/quizImages/quiz1/main.png"
const data=[
    {
        title:"",
        mainImage:"/quizImages/quiz1/main.png",
        options:[
            {
                label:"A",
                url:"/quizImages/quiz1/a.png"
            },
            {
                label:"B",
                url:"/quizImages/quiz1/b.png"
            },
            {
                label:"C",
                url:"/quizImages/quiz1/c.png"
            },
            {
                label:"D",
                url:"/quizImages/quiz1/d.png"
            },
            {
                label:"E",
                url:"/quizImages/quiz1/e.png"
            },
            {
                label:"F",
                url:"/quizImages/quiz1/f.png"
            },
        ]
    },
    {
        title:"",
        mainImage:"/quizImages/quiz2/main.png",
        options:[
            {
                label:"A",
                url:"/quizImages/quiz2/a.png"
            },
            {
                label:"B",
                url:"/quizImages/quiz2/b.png"
            },
            {
                label:"C",
                url:"/quizImages/quiz2/c.png"
            },
            {
                label:"D",
                url:"/quizImages/quiz2/d.png"
            },
            {
                label:"E",
                url:"/quizImages/quiz2/e.png"
            },
            {
                label:"F",
                url:"/quizImages/quiz2/f.png"
            },
        ]
    }
]

export default data